version: "3.5"
services:
  interpreter:
    build: .
    environment:
      ENVIRONMENT: "production"
    volumes:
      - ./assets/fib.json:/var/rinha/source.rinha.json
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2.0GB"